services:
  - type: web
    name: ecommerce-app
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        sync: false
      # Uncomment if using Stripe
      # - key: STRIPE_SECRET_KEY
      #   sync: false
      # - key: STRIPE_PUBLISHABLE_KEY
      #   sync: false